GET https://dbioz2ek0e.execute-api.ap-south-1.amazonaws.com/mockapi/get-employees

###

POST https://reqres.in/api/login
Content-Type: application/json

{
    "email" : "eve.holt@reqres.in",
    "password" : "cityslicka"
}

###

# POST https://reqres.in/api/login
# Content-Type: application/json
# Authorization: Bearer QpwL5tke4Pnpja7X4
# {
#     "email" : "eve.holt@reqres.in",
#     "password" : "cityslicka"
# }